### PR TITLE
feat: drop support for webpack 2 and 3

### PR DESCRIPTION
**Pull request by piotr-oles**
We drop support for webpack < 4.0 to simplify our codebase and prepare for further refactoring.

BREAKING CHANGE: 🧨 Dropped support for webpack 2.0 and webpack 3.0

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]
Noooooiiice! 🤗

**Review by phryneas — APPROVED** [review]
I love it. Finally the index.ts is readable again.

**Comment by johnnyreilly** [comment]
I've moved one of my apps at work to use 4.0.0-beta.4.

So far, so good!

**Pull request merged**
