### PR TITLE
fix `useTypescriptIncrementalApi` flag to work according to docs

### LINKED ISSUE #222: bug: `useTypescriptIncrementalApi` flag is not true by default, even if TS Version > 3
The bug is caused by wrong `this.options.useTypescriptIncrementalApi` ([source code here](https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/03c612ed742e6e6002c32cce2ddfef5bdba7b220/src/index.ts#L572)):

```
USE_INCREMENTAL_API:
            this.options.useTypescriptIncrementalApi === true,
```

the fix should be:

```
USE_INCREMENTAL_API:
            this.useTypescriptIncrementalApi === true,
```

### PR DESCRIPTION
**Pull request by yanivefraim**
`useTypescriptIncrementalApi` doesn't work as supposed to - it is not true by default, for TS version > 3.

fixes #222

### CODE REVIEW

**Comment by johnnyreilly** [comment]
First of all, thanks for this - good catch!

There's now some failing tests which I believe are related to https://github.com/Realytics/fork-ts-checker-webpack-plugin/issues/219

i.e. the incremental compiler has some issues with Vue which we hope will be solved by this PR:

https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/220

~In the meantime, you could fix it by forcing the Vue tests that are failing to *not* use the incremental API. That would work for now. Sound good?~

Actually - better idea: could you apply the changes from this commit to your PR: https://github.com/Realytics/fork-ts-checker-webpack-plugin/commit/90836f2d330024e2e1c7796ffffb2d0ceaf788a5 (apart from the reasons.md that is). That should stop the incremental API being used and the tests should pass.

**Comment by yanivefraim** [comment]
> Actually - better idea: could you apply the changes from this commit to your PR: 90836f2 (apart from the reasons.md that is). That should stop the incremental API being used and the tests should pass.

@johnnyreilly - I cherry-picked 90836f2d330024e2e1c7796ffffb2d0ceaf788a5, without the readme part, wasn't sure about tests, so I just kept them...

**Comment by johnnyreilly** [comment]
Awesome. Thanks!

Could you increment the version in the `package.json` and put an entry in the `CHANGELOG.md` please? I'll then merge and push out a release

**Comment by yanivefraim** [comment]
> Could you increment the version in the package.json and put an entry in the CHANGELOG.md please? I'll then merge and push out a release

@johnnyreilly  - done

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by johnnyreilly** [comment]
Will go out with https://github.com/Realytics/fork-ts-checker-webpack-plugin/releases/tag/v1.0.0-alpha.10

Thanks again!

**Pull request merged**
