### PR TITLE
feat: add devcontainer support

### PR DESCRIPTION
**Pull request by johnnyreilly**
I use a Windows machine; the test pack for the `fork-ts-checker-webpack-plugin` has never entirely worked with Windows.  This is fine; I just switch to WSL and go with it.

This PR adds in support for VS Code's dev containers; see: https://code.visualstudio.com/docs/remote/containers#_getting-started

This helps me and may help other Windows users that would like to contribute.

### CODE REVIEW

**Comment by phryneas** [comment]
When started from linux, this seems to have permission problems - vscode tries to create files in /root, but it runs as user "node", so it doesn't have correct permissions to write there.

```
Run: docker exec 95209b7c27b90a0623404756729da4953c6ef6c63aedeba1399829ba49629277 test -d /root/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f
Installing VS Code Server for commit c7d83e57cd18f18026a8162d042843bda1bcf21f
Run: docker exec 95209b7c27b90a0623404756729da4953c6ef6c63aedeba1399829ba49629277 mkdir -p /root/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f_1567458922703
mkdir: cannot create directory '/root': Permission denied
Command failed: docker exec 95209b7c27b90a0623404756729da4953c6ef6c63aedeba1399829ba49629277 mkdir -p /root/.vscode-server/bin/c7d83e57cd18f18026a8162d042843bda1bcf21f_1567458922703
```

Adding a `    && chmod o-rwX /root \` somewhere in the Dockerfile seems to work, but that's more of a dirty workaround. 
Unfortunately, I haven't tried devcontainers yet, so I don't really have experience with that. But I guess this is a common problem with all devcontainers based on the node container, so we can't be the first with that problem.

**Comment by johnnyreilly** [comment]
That's interesting - I pretty much lifted and shifted the Microsoft example. I think it may have been this one: https://github.com/microsoft/vscode-dev-containers/tree/master/containers/javascript-node-lts-mongo/.devcontainer

Let me double check if I made any significant tweaks...

**Comment by johnnyreilly** [comment]
Unfortunately my first steps into Linux land have resulted in a bricked laptop 😄

@OB6160 and I will reattempt in a month or so; just need to fit a new hard drive and we've a hackathon to prepare for first.

When I'm up and running with Ubuntu I'll take this for a whirl there. Works great on Windows already though 😁

**Comment by ob6160** [comment]
When I get a moment I'll give this a go on my Linux machine & look into a fix

**Comment by phryneas** [comment]
> Unfortunately my first steps into Linux land have resulted in a bricked laptop smile

What did you DO? :D

**Comment by johnnyreilly** [comment]
@ob6160 only do it if you're totally bored - this can wait! (And it's not your fault I'm blocked; it's my dodgy machine 😄)

> What did you DO? :D

Well my XPS had been behaving oddly for a while. It was that that prompted me to get a new one. When @ob6160 and I started attempting to repave the old one with Ubuntu we discovered that the hard drive was trashed midway through reformatting it. C'est la vie 😁

I now have a new hard drive which we'll use to resurrect the machine next month. I'll get there... It's just a matter of time ⌚

**Comment by ob6160** [comment]
@phryneas this patch seems to do the trick on my linux box https://gist.github.com/ob6160/525eb3c6684e5d7104e676c410495a70

Maybe give a rebuild of your devcontainer a go with that change? Not sure why the `runArgs` didn't work though.

**Comment by johnnyreilly** [comment]
I've patched - is that right @ob6160 ?

**Comment by johnnyreilly** [comment]
I think this is now working thanks to @ob6160 help ❤️ 

I want to get a release out there as I've realised that @pelotom's https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/345 didn't trigger a release due to the commit format.  I'm planning to merge this as (AFAIK) it all works and it should be a non-invasive change.  There's nothing in here that can break existing users and it's certainly making it easier for me to work on the plugin 😄 

Unless anyone objects I'm going to merge this PR when the CI goes green later this morning.  This will trigger a release and fix the current live issue that exists with 1.5.1 - see @johnbouma's issue here: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/349

**Review by piotr-oles — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Hopefully this should trigger a release shortly. Travis has been a little flaky for the last couple of days though - so will keep an eye on it

**Pull request merged**
