### PR TITLE
Update chokidar dependence 

### PR DESCRIPTION
**Pull request by popuguytheparrot**
chokidar 3.2.1
Improve Linux RAM usage by 50%. Stability optimizations. Race condition fixes. Windows glob fixes.
chokidar 3.2.1
Improve Linux performance by 50%.
chokidar new major version has update for fsevents 
1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size

### CODE REVIEW

**Review by johnnyreilly — CHANGES_REQUESTED** [review]
We use yarn - please could you regenerate the `yarn.lock` file?

**Comment by johnnyreilly** [comment]
Also your commit isn't following our naming guidance and so wouldn't be mergeable. Please could you follow the guidelines and resubmit your PR?

**Comment by rasane** [comment]
Hi, this is blocked waiting on yarn.lock quite possibly, unaware of this PR, I was looking at #360 and did the same change. Please let me know how you would like to proceed?

**Comment by johnnyreilly** [comment]
I'm going to close this in favour of https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/361 - it looks like that should solve the problem when CI has worked it's way through

**Pull request closed without merging**
