### PR TITLE
feat: implement write-dts mode

### LINKED ISSUE #663: How to emit .d.ts and .d.ts.map files?
I cannot use ts-loader to generate declaration files with this plugin as that'll cause double type checking.
How can I use this plugin and also have declaration files generated?

### PR DESCRIPTION
**Pull request by adriangodong**
This PR adds a new mode called `write-dts`. When selected, the plugin will emit tsbuildinfo, d.ts, and d.ts.map files. This allows the plugin to work together with` ts-loader` (with `transpileOnly` set to `true`) or `babel-loader` and emit type definition files.

Fixes #663, #658

### CODE REVIEW

**Review by piotr-oles — APPROVED** [review]
Code looks great, I will wait for the CI and if everything is green, we're good to merge :) Thanks for the contribution!

**Comment by adriangodong** [comment]
@piotr-oles ping for merge 🙏

**Comment by PierBJX** [comment]
@piotr-oles @onigoetz @adriangodong 

After investigation (look at e2e test), in order to make it work, you need to set the `build` typescript option to `true`.

See the working configuration:
```
module.exports = {
  entry: './foo.ts',
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'ts-loader',
            options: {
              transpileOnly: true,
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new ForkTsChecker({
      typescript: {
        build: true,
        mode: 'write-dts',
      },
    }),
  ],
};

```

I don't know if it was the expected behavior but with this configuration it works. Remove `build: true`, you will see it does not work anymore. Indeed, by default, the value is set to `false`.

**Pull request merged**
