### PR TITLE
Adding a warning message for SIGINT OOM failures

### LINKED ISSUE #357: Build stops after `0.95 'emitting' 'fork-ts-checker-webpack-plugin'`
## Current behavior
My webpack build gets to 95%, and after it emits 'fork-ts-checker-webpack-plugin' the build fails. Although the command exits with status 0, like a success, no build artefacts are generated. With the webpack logs, I see that it only ever gets to 95%, at this step.

```sh
yarn build
yarn run v1.19.1
$ node ./scripts/build_client.js
Ready to start the build.

Creating an optimized production build...
0 'compiling'
0.1 'building' '0/0 modules' '0 active' ''
0.1 'building' '0/1 modules' '1 active' 'multi /home/circleci/project/src/index.tsx'
0.10120000000000001 'building' '1/1 modules' '0 active' ''
...
0.930392156862745 'after chunk asset optimization' 'SourceMapDevToolPlugin'
0.9352941176470588 'asset optimization'
0.9401960784313725 'after asset optimization'
0.9450980392156862 'after seal'
0.95 'emitting'
0.95 'emitting' '@loadable/webpack-plugin'
0.95 'emitting' 'HtmlWebpackPlugin'
0.95 'emitting' 'GenerateSW'
0.95 'emitting' 'fork-ts-checker-webpack-plugin'
 
```

This is the end of the logs, no artefacts are outputted. That is the `build` folder is empty.

## Expected behaviour
The build continues to 100% and the artefacts are outputted.

## Steps to reproduce the issue
I am using a forked version of CRA, but I just run `yarn build` and get this situation.

Here is a sample from my config. [Full config is here](https://hastebin.com/cehagitawe.js).

```js
const ForkTsCheckerWebpackPlugin = require("react-dev-utils/ForkTsCheckerWebpackPlugin");

new ForkTsCheckerWebpackPlugin({
  typescript: resolve.sync("typescript", {
    basedir: paths.appNodeModules
  }),
  async: isEnvDevelopment,
  useTypescriptIncrementalApi: true,
  checkSyntacticErrors: true,
  resolveModuleNameModule: process.versions.pnp
    ? `${__dirname}/pnpTs.js`
    : undefined,
  resolveTypeReferenceDirectiveModule: process.versions.pnp
    ? `${__dirname}/pnpTs.js`
    : undefined,
  tsconfig: paths.appTsConfig,
  reportFiles: [
    "**",
    "!**/__tests__/**",
    "!**/?(*.)(spec|test).*",
    "!**/src/setupProxy.*",
    "!**/src/setupTests.*"
  ],
  watch: [paths.appServer, paths.appSrc],
  silent: true,
  // The formatter is invoked directly in WebpackDevServerUtils during development
  formatter: isEnvProduction ? typescriptFormatter : undefined
});

```

## Environment
 - **fork-ts-checker-webpack-plugin**: react-dev-utils/ForkTsCheckerWebpackPlugin ("react-dev-utils": "^9.0.1",)
 - **typescript**: "typescript": "3.4.5",
 - **webpack**: "webpack": "4.29.6",
 - **os**: circleci

### PR DESCRIPTION
**Pull request by GreenGremlin**
This warning should help identify OOM failures caused by docker killing the service process.

Fixes https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/357

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]
I really like this! What do you think @piotr-oles?

**Comment by phryneas** [comment]
This is great.

**Comment by GreenGremlin** [comment]
One other concern is that when this happens, webpack still exits cleanly. I'm wondering if we should push an error to `compilation.errors` to trigger a webpack build failure.

**Comment by piotr-oles** [comment]
That's a great idea to push error to the `compilation.errors`. It will work only for `async: false`. Could you add this to this PR?

**Comment by GreenGremlin** [comment]
> That's a great idea to push error to the `compilation.errors`. It will work only for `async: false`. Could you add this to this PR?

I don't mind doing that, but it will require more manual testing. Would you be ok with merging this and making that a separate PR?

**Comment by piotr-oles** [comment]
Ok, no problem :)

**Pull request merged**
