### PR TITLE
Fix deploying

### PR DESCRIPTION
**Pull request by piotr-oles**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I was just wondering why TypeScript needs to be a dependency?  Isn't it only needed at build time?  So doesn't it being a `devDependency` work just fine?

Could be completely wrong - just wanted to understand :smile:

**Comment by piotr-oles** [comment]
Yes, you have right, it should not be in dependencies part :) I've just tried to find out how to fix deploy issue. I've fixed first issue - added `skip_cleanup: true` directive in `.travis.yaml` but there is second issue - probably npm key format has been changed or someone regenerated key in our organization. I will check this as soon as possible but I'm affraid it will not be tomorrow :/

**Comment by johnnyreilly** [comment]
Sure - this is probably why I've kept the ts-loader release steps rather manual :wink:

**Comment by johnnyreilly** [comment]
Hey @piotr-oles - any ideas when this will ship?  Sorry to chase - we'd just :heart:  to be able to use v0.2.9 :sunflower:

**Comment by johnnyreilly** [comment]
Hey @piotr-oles, I hope you're well. 

It'd be really nice to be able to use this.  Is there anything I can do to help make a release happen? I appreciate this is done in your spare time and so if I can help make this easier then I'd like to offer my services.

**Comment by johnnyreilly** [comment]
Hey @piotr-oles, because I'm impatient for the 0.2.9 release I've set up a short-term repo here:  https://github.com/typestrong/fork-ts-checker-webpack-plugin

nb The repo above will be removed from GitHub once 0.2.9 is released to npm.  This is just for those impatient people out there (well, me mostly :wink:)  FWIW I noticed that fork-ts-checker-webpack-plugin won't compile with TypeScript 2.6.  I fixed that here: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/commit/448ba32dd25cb1cb35ff0cb211a08b59a2ba65f8

I'll submit a PR to the initial repo for you

**Comment by johnnyreilly** [comment]
Done - see here: https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/69

**Comment by piotr-oles** [comment]
Thank you, PR merged :)

**Comment by piotr-oles** [comment]
@smonteil - Could you send me the actual npm key by email? There are lot of impatient people waiting for v0.2.9 :)

**Comment by johnnyreilly** [comment]
Just to second what @piotr-oles says @smonteil: I'd love to use 0.2.9 from npm rather than my own fork. Please could you provide the key? Thanks!

**Comment by piotr-oles** [comment]
@vnguyenhuu @etienne-dldc ? :)

**Comment by etienne-dldc** [comment]
Hi guys,

sorry for blocking the release 😞,
the key should have been send to you @piotr-oles, please take a look and tell me if it's ok.

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by piotr-oles** [comment]
@etienne-dldc please send it to my work email: piotr.oles@codibly.com - I don't have access to Realytics mail :)

**Comment by piotr-oles** [comment]
@etienne-dldc ok, I missed it - you send it already there , thanks, I will check it asap :)

**Comment by piotr-oles** [comment]
@etienne-dldc Thank you, @johnnyreilly fork-ts-checker-webpack-plugin is now available in version 0.2.9 on npm :)

**Comment by johnnyreilly** [comment]
Wonderful! Well done all!!!!

**Pull request merged**
