### PR TITLE
feat: add `context` option for typescript reporter

### PR DESCRIPTION
**Pull request by piotr-oles**
Add the `context` option to support the usage of external tsconfig.json files.

✅ Closes: #297

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]

**Comment by shayke** [comment]
Thanks for the quick fix!

I've tested this and it works great, one thing that is still different, i get:
`TS18003: No inputs were found in config file 'tsconfig.json'. Specified 'include' paths were '["**/*"]' and 'exclude' paths were '[]'.`

Now, my setup is such that I potentially use webpack without ts files at all (only scss for example).
I understand that `tsc -p .` on a project with no ts files gives this error but when using `ts-loader` alone (`transpileOnly: false`) I don't get such an error and webpack builds successfully.

Any ideas? (other than disabling this plugin if no ts files, I'd rather it silently continue like ts-loader with no errors maybe?).

Thanks!

**Comment by piotr-oles** [comment]
If you want to skip this error, you can configure it in the plugin:
```js
  new ForkTsCheckerWebpackPlugin({
    issues: {
      exclude: [{ code: 'TS18003' }]
    }
  })
```

**Pull request merged**
