### PR TITLE
file path for webpack base on process.cwd 

### PR DESCRIPTION
**Pull request by piotr-oles**
Based on the #512 - added e2e tests

### CODE REVIEW

**Comment by eamodio** [comment]
@piotr-oles I was hoping this change would fix an issue I am seeing where the error reporting isn't based on the cwd, but a nested sub-folder.

In my case ([here](https://github.com/eamodio/vscode-gitlens/blob/466f2aa04b6b7d8cafd94a0e0c3a40fbaa470d7a/webpack.config.js#L236-L247)), I have 2 parallel webpack configs (1 for my extension & 1 for its webviews). The error reporting for the extension work fine (as the files are in `src/`), but the reporting for the webviews are relative to `src/webviews/apps` which causes issues with problem matchers (in vscode).

Am I wrong in thinking that these changes would have resolved this?

**Comment by piotr-oles** [comment]
Could you try to upgrade to `6.0.0-alpha.3`? You use `6.0.0-alpha.2` which doesn't contain this change:
```
fork-ts-checker-webpack-plugin@6.0.0-alpha.2:
  version "6.0.0-alpha.2"
  resolved "https://registry.yarnpkg.com/fork-ts-checker-webpack-plugin/-/fork-ts-checker-webpack-plugin-6.0.0-alpha.2.tgz#9a3ff105f1ad9905d344691142917a4a26742a6c"
  integrity sha512-wpgTOeOJ2QADI6wy0zqOsepfQDCK1E3Msx8xsCmGDjNjPS5lfx9PwxXg1VfGfsqw/uXMv2qgZc49KKFXH/w/KA==
  dependencies:
    "@babel/code-frame" "^7.8.3"
    "@types/json-schema" "^7.0.5"
    chalk "^4.1.0"
    chokidar "^3.4.2"
    cosmiconfig "^6.0.0"
    deepmerge "^4.2.2"
    fs-extra "^9.0.0"
    memfs "^3.1.2"
    minimatch "^3.0.4"
    schema-utils "2.7.0"
    semver "^7.3.2"
    tapable "^1.0.0"
```

**Comment by eamodio** [comment]
Yeah, I tried alpha.3 and didn't see any change:

https://github.com/eamodio/vscode-gitlens/blob/8fb3a499dbb44a9ae5e3799499e008527d4597dc/yarn.lock#L2670-L2686

**Comment by eamodio** [comment]
@piotr-oles any idea on this one?

**Comment by piotr-oles** [comment]
I haven't time to look into this :/ I hope I will find some time this week :)

**Comment by piotr-oles** [comment]
@eamodio I found a bug - fix is on the way :)

**Pull request merged**
