### PR TITLE
Fix webpack4 hooks not being initialized properly

### PR DESCRIPTION
**Pull request by liangchunn**
webpack4 hooks should be initialized with the corresponding callback params listed in [the 'Plugin Hooks' section of the README.md](https://github.com/Realytics/fork-ts-checker-webpack-plugin#plugin-hooks) 

I managed to find a reference of the usage of `SyncHook` [here](https://github.com/webpack/webpack/issues/6064#issuecomment-349405474)

This was discovered while I was using `fork-ts-checker-notifier-webpack-plugin`, where tapping `compiler.hooks.forkTsCheckerReceive` yielded `undefined` for `diagnostics` and `lints`

### CODE REVIEW

**Comment by johnnyreilly** [comment]
This looks good to me. The build failure is against webpack 2 and is just a flaky test I believe. I think we should merge this @piotr-oles. What do you think?

**Review by piotr-oles — APPROVED** [review]

**Comment by piotr-oles** [comment]
Thank you @liangchunn for this fix - will be released in next version :)

**Comment by johnnyreilly** [comment]
Hey @piotr-oles / @liangchunn,

I've published a new release of the fork-ts-checker-webpack-plugin on the unofficial alpha channel: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin which people can use until fork-ts-checker-webpack-plugin ships next time.

My [notifier plugin](https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin) doesn't work without @liangchunn's changes. If anyone else needs this fix then they can use unofficial alpha in the meantime.

**Comment by liangchunn** [comment]
@johnnyreilly Thanks for publishing. I was holding off from migrating my projects, but now I can start.

**Comment by johnnyreilly** [comment]
My pleasure!

**Comment by developer-lindner** [comment]
"Cannot read property 'tap' of undefined"

at module.exports.ForkTsCheckerNotifierWebpackPlugin.apply (/node_modules/fork-ts-checker-notifier-webpack-plugin/index.js:99:41).

There seems to be an issue still.

**Comment by liangchunn** [comment]
@developer-lindner 
Everything works fine with me with the beta channel mentioned by johnnyreilly.

~Are you using `TypeStrong/fork-ts-checker-webpack-plugin`?~
~Try removing your `node_modules` and `package-lock.json` and running `npm install` again if this issue still persists.~

_EDIT_: Resolved in https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/issues/2#issuecomment-371457927

**Pull request merged**
