### PR TITLE
Update deploy key

### PR DESCRIPTION
**Pull request by piotr-oles**

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I'm not sure the release happened @piotr-oles. I can see it on GitHub https://github.com/Realytics/fork-ts-checker-webpack-plugin/releases/tag/v0.2.9 but not on npm :sad: Do you know what happened?

**Comment by piotr-oles** [comment]
Yes, it looks like someone from Realytics regenerated npm key and I have to wait for them to send me new one (because I'm not working there now)

**Comment by johnnyreilly** [comment]
Oh I see.  That's tricky!  Is this going to be a problem every time you try to release?

**Comment by piotr-oles** [comment]
No, it's the first time :) I'm hope it will not be regenerated in the future :)

**Comment by johnnyreilly** [comment]
Me too!

**Pull request merged**
