### PR TITLE
Fix for android when doing yarn start

### PR DESCRIPTION
**Pull request by freefaint**
Added hack to prevent crashing apps using this one when os.cpus returns undefined

### CODE REVIEW

**Review by johnnyreilly — COMMENTED** [review]
What does `os.cpus()` return on Android? `0`? A falsey value?

**Comment by freefaint** [comment]
It returns undefined and you're waiting for array trying to get its length

**Comment by freefaint** [comment]
Android 8.1

**Comment by johnnyreilly** [comment]
I wonder if `os.cpus() || 1` might achieve the same goal but be a little clearer?

**Comment by freefaint** [comment]
You are waiting that os.cpus() returns an array, if you call os.cpus().length. So in case of undefined we need an array that has one element. It's safe, because in that case we don't really know real number of cores in device cpu.

I checked my code, it works) Thank you)

**Comment by freefaint** [comment]
The problem Is that you're trying to get the length of undefined. It crashes if you get undefined from cpus(). so we need to prevent undefined before .length. the safest way is to polyfill array that has 1 element. This fix will not change your logic , just will prevent crash

**Comment by johnnyreilly** [comment]
Sorry - I wrote the wrong thing; first time.  What I meant to write was: 

```
os.cpus() ? os.cpus().length : 1;
```

This should have the same effect as yours but be more obvious in its intent.  What I mean is, when I read `(os.cpus() || [null]).length` my immediate thought is "what's the significance of `null`"?  Why `null`?

You have to think some more before you draw the conclusion that `null` is not significant at all; it could be any value at all; all you care about is an array having a single member so you can `.length`.  

I'm very much a fan of code being very clear and easy to reason about; hence my suggestion.  What do you think?

**Comment by freefaint** [comment]
Ok, null is shit really)

But think about your example.

os.cpus().length || 1

Do you understand, thit this will cause an error. You're trying to get length property from undefined still in this code. This moment crashes the app

**Comment by freefaint** [comment]
Maybe this solving

(function() { try { return os.cpus().length} catch (e) { return 1 } })()

**Comment by johnnyreilly** [comment]
> Do you understand, thit this will cause an error. You're trying to get length property from undefined still in this code. This moment crashes the app

You're right - that's why I suggested this: (bug in my initial idea)

`os.cpus() ? os.cpus().length : 1;`

**Comment by freefaint** [comment]
In this way you decrease performance because call cpus() 2 times so thats why i solved it in my way...

But your code solves the problem) thank you)

**Comment by johnnyreilly** [comment]
> In this way you decrease performance

A fair point. However, this is something that's run once only I think (upon instantiation); I'm pretty sure the difference to consumers will be so unnoticeable as to not matter. I'd lay good money that V8 optimises this away to nothing anyway :smile:

**Comment by johnnyreilly** [comment]
Would you like to tweak the solution to my suggestion?  I don't see any reason why we couldn't merge that.

**Comment by freefaint** [comment]
Im sorry, i'm bad at english, i'm afraid i cant fully understand your last comment :) If I understand you right, you wanted me to change the solution as we descided :) It's ready)

**Comment by johnnyreilly** [comment]
That's great! Thanks. 

@piotr-oles you happy for us to merge?

**Comment by piotr-oles** [comment]
Looks good - thank you for your work :)

**Comment by freefaint** [comment]
thank you :)

now you we can launch react typescript applications with yarn in android environment (i used termux console emulator)

unbeliveable!!!

**Pull request merged**
