### PR TITLE
fix: bind computeContextPath before passing it to map

### LINKED ISSUE #300: Cannot read property 'compiler' of undefined in v1.3.6
## Current behavior
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'compiler' of undefined
```

## Environment
 - **fork-ts-checker-webpack-plugin**: v1.3.6

The bug was introduced in this commit https://github.com/Realytics/fork-ts-checker-webpack-plugin/commit/489dc89b1d4b043128837c8588d2c3c9ad6dd4ec

### PR DESCRIPTION
**Pull request by phryneas**
This should fix #300 - an error occured after merging #299 when `options.watch` was not undefined.

I might add tests later in a separate PR, but get this merged ASAP before more people have this problem.

### CODE REVIEW

**Review by johnnyreilly — DISMISSED** [review]
Nice work! 🚢 it!

**Comment by phryneas** [comment]
Argh, adding the tests last minute did reset the approval status :D please re-approve @johnnyreilly  :)

**Review by johnnyreilly — APPROVED** [review]
Done!

**Comment by phryneas** [comment]
Bad thing to note: sometimes the jest tests time out. (already before this PR :disappointed: )
I've got to investigate that. For now, if it happens you can just restart the Travis Build. But it's not optimal :/

**Comment by johnnyreilly** [comment]
At least the restart possibility is there. TBH ts-loader has a bunch of flaky integration tests which every now and then need a little restart love. There's worse things 😁

**Pull request merged**
