### PR TITLE
docs: update release documentation

### PR DESCRIPTION
**Pull request by piotr-oles**
As we discussed in the #275 I've added documentation for the release process

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Lovely - very clear!

**Review by phryneas — APPROVED** [review]
Yup, looks good.

**Comment by johnnyreilly** [comment]
Cool - do we do the beta -> master PR now?

Or are you hoping to combine with https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/275#pullrequestreview-232872963

**Comment by phryneas** [comment]
@johnnyreilly I think you can safely pull the trigger in #275 :)

**Comment by johnnyreilly** [comment]
Bad news - when you try you get this message:

> This branch can't be rebased

I'd send a screenshot but I'm on my phone

**Comment by johnnyreilly** [comment]
How did you get it to work? Can you just not rebase on a phone?

**Pull request merged**
