### PR TITLE
fix: only invoke WDS tap when there are issues

### PR DESCRIPTION
**Pull request by tessro**
👋🏼 Hi! We were seeing a strange behavior in our app where it would spontaneously perform a full-page HMR about 15s after booting. I traced it to `fork-ts-checker-webpack-plugin`'s `async` mode invoking `webpack-dev-server`'s `sync` tap, which was causing an HMR even if no issues were reported.

I was able to resolve the issue by modifying `fork-ts-checker-webpack-plugin` to only invoke `webpack-dev-server`'s tap if any issues were found. This eliminates the unneeded reload. I believe this change is safe based on my testing, but this is my first time diving into the codebase so let me know if I'm thinking about this the wrong way! Thanks for considering this PR. 🍻

### CODE REVIEW

**Comment by piotr-oles** [comment]
Thanks for the PR, looks good 👍

**Review by piotr-oles — APPROVED** [review]

**Comment by tessro** [comment]
Hi, is there any chance this can be merged and released soon? Thanks!

**Comment by piotr-oles** [comment]
Ah sorry, I was waiting for other release to finish and forgot about it :D

**Comment by tessro** [comment]
No problem! Thank you so much. 🙏🏼

**Pull request merged**
