### PR TITLE
feat: remove Yarn PnP extension as it's redundant

### PR DESCRIPTION
**Pull request by piotr-oles**
Thanks to yarn pnpify, we don't need to patch TypeScript anymore.

BREAKING CHANGE: 🧨 Removed Yarn PnP extension (and related options) as it became
redundant

### CODE REVIEW

**Review by arcanis — APPROVED** [review]
To be exact, PnPify isn't what makes Yarn works with TypeScript. Instead, Yarn ships with a limited set of patchfiles (that we maintain ourselves) that are applied on known "broken" packages.

TypeScript is one of them, and its patchfile applies an automatic merge of https://github.com/microsoft/TypeScript/pull/35206. Same result, except that you don't even have to use PnPify to have TypeScript support 😃

**Comment by piotr-oles** [comment]
@arcanis Thanks for the clarification, I will update the commit message on merge :)

**Review by johnnyreilly — APPROVED** [review]

**Pull request merged**
