### PR TITLE
fix os.cpus is not a function

### PR DESCRIPTION
**Pull request by superlbr**
as mentioned in #150

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Great! Do you want to update the `package.json` and `changelog.md` as well please?

**Comment by superlbr** [comment]
after `yarn outdated`, packages need upgrade
```
@types/node
@types/resolve
chai
css-loader
mocha
mock-require
sinon
ts-loader
```

**Comment by johnnyreilly** [comment]
> after yarn outdated, packages need upgrade

Don't worry - we'll handle that later

**Comment by johnnyreilly** [comment]
I'm really sorry but for some reason the CI refuses to trigger and GitHub won't let me merge (not even manually).  Could you try resubmitting this change please?  I figure that should work okay.

**Comment by johnnyreilly** [comment]
Unblocked and merged. Thanks!

**Pull request merged**
