### PR TITLE
feat: remove eslint support

### PR DESCRIPTION
**Pull request by piotr-oles**
Let's remove eslint support on alpha channel. I will remove unnecessary abstractions in the next PRs. 
The goal of the 7.0.0 release is to drop support for Node 10 (as is no longer supported), webpack 4 (this will fix types issues), and old versions of TypeScript (2+ years old).
I will still try to maintain version 6 by fixing bugs :)

BREAKING CHANGE: 🧨 ESLint no longer supported by the plugin

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]

**Comment by cmlenz** [comment]
I couldn't find any discussion about this, so I'm curious: what is the rationale behind removing ESLint support. And what is the recommended replacement for projects that use this now?

**Comment by piotr-oles** [comment]
https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/601 :)

**Pull request merged**
