### PR TITLE
fix: eslint excludes .json & ignored files (#316)

### LINKED ISSUE #316: Using eslint support and seeing warnings for ignored files
## Current behavior
I've switched [GitLens](https://github.com/eamodio/vscode-gitlens/tree/develop) over to use the new eslint support (thanks for that!) but I'm running into a minor issue. At first, it was trying to lint one of my `json` files, but I added that file to my `.eslintignore` file. But it still seems to be trying to lint that file (and another file from `node_modules` which is ignored by default in eslint), which outputs a warning for each file -- saying that it is ignored

```
WARNING in C:\Users\Eric\code\vscode-gitlens\node_modules\vsls\vscode.ts
WARNING in C:\Users\Eric\code\vscode-gitlens\node_modules\vsls\vscode.ts(undefined,undefined):
    undefined: File ignored by default. Use "--ignore-pattern '!node_modules/*'" to override.

WARNING in C:\Users\Eric\code\vscode-gitlens\src\emojis.json
WARNING in C:\Users\Eric\code\vscode-gitlens\src\emojis.json(undefined,undefined):
    undefined: File ignored because of a matching ignore pattern. Use "--no-ignore" to override.
```

## Expected behavior
I would expect no warnings to be output for those ignored files

## Steps to reproduce the issue
I don't have a simple sample, but you can see it with the GitLens repo (on the `develop` branch)

1. Clone https://github.com/eamodio/vscode-gitlens.git
1. Checkout `develop`
1. Run `npm install` to install all the deps
1. Run `npm run watch`

## Issue reproduction repository
https://github.com/eamodio/vscode-gitlens.git

## Environment
 - **fork-ts-checker-webpack-plugin**: `1.4.2`
 - **typescript**: `3.5.3`
 - **eslint**: `6.0.1`
 - **webpack**: `4.35.3`
 - **os**: Windows 10

### PR DESCRIPTION
**Pull request by eamodio**
Fixes #316 

/cc @johnnyreilly

### CODE REVIEW

**Review by johnnyreilly — APPROVED** [review]
Great work! Thanks ♥️🌻

**Comment by johnnyreilly** [comment]
This should be out in the next hour or two. Thanks @eamodio!

**Comment by eamodio** [comment]
Thank, you, it was your solution 😉

**Comment by johnnyreilly** [comment]
You say that... It was you that brought `sensitivity: 'accent'` to the party 😁

**Comment by eamodio** [comment]
Haha -- yeah, such a strange api for doing an insensitive string compare. Couldn't be something like `.equalsIgnoreCase` or something obvious. But this is JS after all 😉

**Comment by benkaiser** [comment]
@piotr-oles has this regressed? I'm not seeing any usages of `.isPathIgnored` in the codebase now.

**Pull request merged**
