### PR TITLE
docs: update babel-loader docs for type-only modules watch

### PR DESCRIPTION
**Pull request by piotr-oles**
This update should help with the `babel-loader` issues described in the #36 :)

### CODE REVIEW

**Comment by dmarkow** [comment]
I'm using babel-typescript. This update says "If you use **TypeScript >=3.8.0**, you can fix it:" however I just tested these recommendations (setting `onlyRemoveTypeImports` to `true`) and updating a types-only file is still not triggering a build. I need to fully restart webpack to get it to recognize my updates.

**Comment by piotr-oles** [comment]
Thanks for the feedback. Is this file imported somehow by another file or is it just a reference / ambient context? This is not an ultimate solution, it should fix the same cases as `"importsNotUsedAsValues": "preserve"` which doesn't mean it will fix all cases. I'm thinking about a better solution but I don't have time to implement it.

**Review by johnnyreilly — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Nice! 👍

**Pull request merged**
