### PR TITLE
minor release - update docs

### PR DESCRIPTION
**Pull request by phryneas**
Let's get this into master :)

Also, let's test what GH does with commit hashes on a rebase ;)

Edit: oh, and @piotr-oles, please you do the rebase - the current commit is already authored by me, so maybe in my case it wouldn't change the hash no matter what.

### CODE REVIEW

**Review by piotr-oles — APPROVED** [review]

**Comment by piotr-oles** [comment]
You were right :(

**Comment by phryneas** [comment]
Yup :( 
See #284 - I hope we can find a more elegant solution but that might be a last resort.

**Comment by phryneas** [comment]
Oh, could you please work your magic again and push the new master onto beta? Before the next PR get's based of one of the duplicate commits ^^

**Pull request merged**
