### PR TITLE
Set-up GitHub Actions

### PR DESCRIPTION
**Pull request by piotr-oles**
I would like to test GitHub Actions as Travis CI is very slow and flaky last time

### CODE REVIEW

**Comment by johnnyreilly** [comment]
This looks cool! Looks like we still have some failing tests?

**Comment by piotr-oles** [comment]
The tests were failing on Windows - we didn't run them on the Travis :) I will comment Windows for now as an error occurs on the multi-process mode and we want to drop support for this anyway.

**Comment by johnnyreilly** [comment]
@piotr-oles - did you want to swap the badges in the readme as well? The Travis badge is still there and there isn't a badge in place for the GitHub actions build.

**Comment by piotr-oles** [comment]
Good catch - I will change badges :)

**Pull request merged**
