### PR TITLE
refactor(dependency): update babel-code-frame to @babel/code-frame

### LINKED ISSUE #408: Bump babel dependency to @babel/code-frame
## Feature motivation

I have a large project that's having issues with conflicting versions of `chalk` being installed. Wrong versions are being picked up in places (which is the individual package's fault).

`fork-ts-checker-webpack-plugin` has a dependency on `babel-code-frame` which in turn pulls in `chalk@1`. For me this is the only package that uses `chalk@1` so I'd like to be able to update it.

Looks like the babel package has now been renamed to `@babel/code-frame` which is where any updates are being published. That depends on `chalk@2` so allows me to update and hopefully drop the conflict.

## Feature description

Reference the new `@babel/code-frame` package in package.json to allow users to upgrade it

### PR DESCRIPTION
**Pull request by andyrooger**
Update code-frame dependency from v6 to v7 so that we can drop the chalk v1 dependency.

Closes #408

### CODE REVIEW

**Comment by andyrooger** [comment]
I've set the dependency to ^7.5.5 because ^7.0.0 has issues with importing @babel/highlight. I can specify latest instead if you prefer though.

**Review by johnnyreilly — DISMISSED** [review]

**Comment by johnnyreilly** [comment]
We seem to have a failing test?

**Comment by andyrooger** [comment]
We do... It's failing to clean up after the tests by the look of it.

Each time I run these actions it seems to fail on a different OS using webpack 5, node 8. Can see if it does the same this time, but I'm wondering if this is just an issue with webpack alpha finishing when we expect.

Is there a good way to try these tests on latest master to see if they're still passing repeatably?

**Comment by andyrooger** [comment]
So they're all passing now... all I've changed is the commit author.

**Comment by johnnyreilly** [comment]
Flaky tests are the worst! @piotr-oles are you happy for us to merge?

**Review by piotr-oles — APPROVED** [review]

**Comment by piotr-oles** [comment]
Looks good. I think we should update the semantic-release config to trigger patch release for `refactor` commits. Give me a few minutes, I will send you what to change.

**Comment by piotr-oles** [comment]
I have created a new PR: #410 to update the semantic-release configuration. We can merge this PR later.

**Comment by andyrooger** [comment]
In case you hadn't already noticed, it looks like refactors don't appear in the release notes even though they do trigger releases. The github release looks blank for 4.1.4. Release itself is working great for me though. :)

**Pull request merged**
