### PR TITLE
Resolve all non TS module with simple concatenation (vue)

### PR DESCRIPTION
**Pull request by Toilal**
Alternative for #86 

It seems that we can handle wildcard module names the same way we handle relative module name (by building the "full" module name). TypeScript seems to be able to solve paths like `/home/toilal/project/test-import/src/components/#/components/Dummy.vue` making manual building from `ts.compilerConfig` just useless.

### CODE REVIEW

**Comment by prograhammer** [comment]
@Toilal 

You've removed the ability to handle wildcards here and you are assuming every module path is relative to its containing file. TypeScript will not be able to find the module, if it contains a wildcard, because we are not using the standard module resolution.

**Comment by Toilal** [comment]
Yes, it seems wildcards can be resolved internally by typescript when using "full path module names". Everything is working properly according to `compilerOptions.paths` in tsconfig. 

Can you give it a try ?

**Comment by prograhammer** [comment]
Just from looking at it, `@/test.vue` isn't equal to `/con/tain/ing/@/test.vue`?

Let me give it a try though...

**Comment by Toilal** [comment]
You may try on this sample project: https://github.com/Toilal/vue-webpack-template/tree/test-%23-import, but you have to compile and link the PR #87.

**Comment by Toilal** [comment]
Assuming you have `paths: { '@/*' : 'src/*}` in tsconfig.json, resolving `@/ImportedComponent.vue` to `/home/toilal/project/app/@/ImportedComponent.vue` is enough, it will effectively load `/home/toilal/project/src/ImportedComponent.vue` but you don't need to build this real path manually.

SourceComponent.vue
```vue
<template>
...
</template>
<script lang="ts">
import ImportedComponent from '@/ImportedComponent.vue'

...
</script>
```

(Maybe that's why there's no API in TypeScript to build this realpath :p)

**Comment by prograhammer** [comment]
`Containing file` is the file that imported the module. Therefore `@/component.vue` is not equal to `[path of containing file]/@/component.vue`.

**Comment by Toilal** [comment]
Just updated my previous message ... Is it more clear ?

**Comment by prograhammer** [comment]
@Toilal It doesn't work.

1. TypeScript can't find the modules in my project:

```
ERROR in /home/david/projects/code/pwa-test/src/app.vue(16,19):
TS2307: Cannot find module '@/components/hello.vue'.
ERROR in /home/david/projects/code/pwa-test/src/app.vue(17,17):
TS2307: Cannot find module '@/components/bar.vue'.
ERROR in /home/david/projects/code/pwa-test/src/main.ts(3,17):
TS2307: Cannot find module '@/app.vue'.
```
2. You updated the tests to rig them to statements that aren't really true. `@/app.vue` is not equal to `/david/projects/code/pwa-test/src/@/app.vue` (the containing file was /david/projects/code/pwa-test/src/main.ts and happens to be in the same folder as app.vue).

**Comment by Toilal** [comment]
Could you push your sample to github please ? Can't understand why everything is OK on mine.

**Comment by prograhammer** [comment]
Updated my previous comments to be clearer as well (had a mistake in them). Trying now with your repo to see what is happening for you...

**Comment by Toilal** [comment]
It's configured to have 2 wildcards

```
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"],
      "#/*": ["app/*"]
    },
```

`app/components/Dummy.vue` is imported from `src/components/HelloWorld.vue` using `#/components/Dummy.vue`.

**Comment by prograhammer** [comment]
I just installed your template and you are using relative paths here: `import App from './App.vue'` and `import HelloWorld from './components/HelloWorld.vue'`.

Can you just build a sample project, and include your PR too and give us a link. I suspect in that process you'll also see what I'm saying is the problem. :smile:

**Comment by Toilal** [comment]
You mean if I use `@` and `#` everywhere, it will fail ?

**Comment by prograhammer** [comment]
So let me explain the code. The `containing file` is the file that imported the module. For example, `main.ts` is the file that imports `app.vue`:

```
// /david/projects/code/example/src/main.ts
import Vue from 'vue'
import App from '@/app.vue`
```
So this PR will give TypeScript the module path as `/david/projects/code/example/src/@/app.vue`. That's incorrect.

Now let's look at another example:

```
// /david/projects/code/example/src/app.vue
import Hello from '@/components/hello.vue`
```
Now TypeScript will look for the module at: `/david/projects/code/example/src/@/components/hello.vue`. That is incorrect.

Make sense?

**Comment by Toilal** [comment]
I have updated the sample project, it now includes the build of this PR as dependency. It's still working when everything is imported with '#' and '@'. https://github.com/Toilal/vue-webpack-template/tree/test-%23-import

I agree it looks incorrect. But actually it works on this sample, so from my point of view it seems there's another layer in TypeScript that handle the conversion of `/david/projects/code/example/src/@/components/hello.vue` to `/david/projects/code/example/src/components/hello.vue` based on `compilerOptions.paths` configuration.


yarn build output (Errors appears 2 times because there's 2 parralel builds, 1 for the demo app and 1 for the lib)
```
toilal@toilal-ubuntu:~/idea-projects/test-import$ yarn build
yarn run v1.3.2
$ node build/build.lib.js && node build/build.js
⠋ building for production...Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
⠹ building for production...ts-loader: Using typescript@2.6.2 and /home/toilal/idea-projects/test-import/tsconfig.json
⠸ building for production...ts-loader: Using typescript@2.6.2 and /home/toilal/idea-projects/test-import/tsconfig.json
Hash: 7f876af6ba917bb2520d1aa03736ce4aa36365bf
Version: webpack 3.10.0
Child
    Hash: 7f876af6ba917bb2520d
    Time: 3367ms
               Asset       Size  Chunks             Chunk Names
         vue-test.js    20.3 kB       0  [emitted]  vue-test
        vue-test.css  286 bytes       0  [emitted]  vue-test
     vue-test.js.map    18.1 kB       0  [emitted]  vue-test
    vue-test.css.map  583 bytes       0  [emitted]  vue-test
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (13,1): Type '"string"' is not assignable to type 'number'.
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (15,2): Expected 1 arguments, but got 0.
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (9,22): Unnecessary semicolon
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (12,5): 'a' is declared but its value is never read.
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (13,5): " should be '
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (17,10): " should be '
    
    ERROR in /home/toilal/idea-projects/test-import/app/App.vue
    (18,22): Unnecessary semicolon
Child
    Hash: 1aa03736ce4aa36365bf
    Time: 3833ms
                  Asset       Size  Chunks             Chunk Names
        vue-test.min.js    7.29 kB       0  [emitted]  vue-test
           vue-test.css  195 bytes       0  [emitted]  vue-test
       vue-test.min.css  195 bytes       0  [emitted]  vue-test
    vue-test.min.js.map      21 kB       0  [emitted]  vue-test
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (13,1): Type '"string"' is not assignable to type 'number'.
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (15,2): Expected 1 arguments, but got 0.
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (9,22): Unnecessary semicolon
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (12,5): 'a' is declared but its value is never read.
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (13,5): " should be '
    
    ERROR in /home/toilal/idea-projects/test-import/app/app-components/Dummy.vue
    (17,10): " should be '
    
    ERROR in /home/toilal/idea-projects/test-import/app/App.vue
    (18,22): Unnecessary semicolon

  Build failed with errors.

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by prograhammer** [comment]
But also consider this scenario:

```
// /david/projects/code/example/src/features/foo.vue
import '@/components/bar.vue'
```

Now you have `@/components/bar.vue` turned into `/david/projects/code/example/src/features/@/components/bar.vue`. 

Notice that bar is really located in `src/components` not `src/features/components`.

I have to run for a bit so I'll check your build tonight.

**Comment by Toilal** [comment]
K, i'll go too, but the sample now includes this use case, `app/app-components/Dummy.vue` is imported from `src/components/HelloWorld.vue` using `#/app-components/Dummy.vue`.

Maybe it works because of consistent aliases in webpack configuration ?

build/webpack.base.conf
```
  resolve: {
...
    alias: {
      'vue$': 'vue/dist/vue.esm.js',
      '@': resolve('src'),
      '#': resolve('app')
    },
...
  },
```

**Comment by Toilal** [comment]
When I remove those webpack aliases, `yarn build` just hang and `yarn dev` display an import error for `main.ts` fail importing `#/App.vue` !

**Comment by prograhammer** [comment]
Lol! Weird! I'll be back on tonight to take a peek.

**Comment by Toilal** [comment]
I close this PR, it makes code simpler, but I can't really understand why it works on my project. #86 seems safer and will do the job.

**Pull request closed without merging**
