### PR TITLE
docs(readme): fix formatting

### PR DESCRIPTION
**Pull request by kaykayehnn**
The code sample collapsible block wasn't working due to improper indentation and there was a duplicated paragraph.

### CODE REVIEW

**Review by phryneas — COMMENTED** [review]
This is very cool, thank you.

We'll gladly accept this, but I would ask two things from you due to our workflow:
* could you please change the PR to go against the `beta` branch instead of the `master` branch? You can do that by just editing the PR, no need to make a new one.
* if you want these changes to be attributed in the next release's Changelog, your commit message needs to follow the [commit message guidelines](https://github.com/Realytics/fork-ts-checker-webpack-plugin/blob/master/CONTRIBUTING.md#commit-message-guidelines) - it would be great if you could reword your commit message :)

**Comment by phryneas** [comment]
Oh, and one (more or less unrelated) thing: we were thinking about splitting the README in multiple files because it is getting very long. We'd be happy for any PR in that direction in case you want to contribute further :)

**Comment by phryneas** [comment]
@piotr-oles it seems that the rebase merges we do always create a new commit hash even if it isn't needed - leading to different commits on `master` and `beta` :cry: 

@kaykayehnn I'm really sorry, that commit chaos isn't your fault at all, we're still trying to get a new merging workflow to work. If you allow me to push to your branch, I can fix that for you if you want me to.

**Comment by kaykayehnn** [comment]
@phryneas Please do, I'm not sure how to resolve it

**Comment by phryneas** [comment]
@piotr-oles lol, did we just do opposing things at the same moment? Don't fix me, I'll follow you :D

**Comment by piotr-oles** [comment]
I've deleted the messed up beta branch and created it from the master - now it should stay in sync (yes, I thought so many times before...)

**Review by piotr-oles — APPROVED** [review]

**Review by phryneas — APPROVED** [review]
Okay, now everything is fine from my side :+1:

**Comment by phryneas** [comment]
@piotr-oles unfortunately, it won't :disappointed: [I found this in the documentation](https://help.github.com/en/articles/about-pull-request-merges#rebase-and-merge-your-pull-request-commits) of github:

> The rebase and merge behavior on GitHub deviates slightly from git rebase. Rebase and merge on GitHub will always update the committer information and create new commit SHAs, whereas git rebase outside of GitHub does not change the committer information when the rebase happens on top of an ancestor commit. 

So, doing a rebase from beta to master through the github UI will always duplicate commits and lead to a mess :/ Maybe there is some 3rd party bot GUI integration we can use to just always fast-forward master to the latest commit of beta?

**Comment by piotr-oles** [comment]
There was additional commit on the beta branch - I think that was the problem. The commits on the master didn’t change - check the Releases page - commits from the beta releases are on the master with the same hash. I think that the GitHub doc is just a little bit misleading - I think they meant that they change committer information when rebase is not a fast-forward :) Let’s give the last chance to this setup :)

**Comment by phryneas** [comment]
> There was additional commit on the beta branch - I think that was the problem. The commits on the master didn’t change - check the Releases page - commits from the beta releases are on the master with the same hash. I think that the GitHub doc is just a little bit misleading - I think they meant that they change committer information when rebase is not a fast-forward :) Let’s give the last chance to this setup :)

I'm pretty sure there were the same commits with different hashes, but I guess the fastest way to test this is just one more release :D

Anyways, I've merged this. Thank you very much @kaykayehnn ! :heart:

**Pull request merged**
