### PR TITLE
Work in progress: add eslint typescript support

### PR DESCRIPTION
**Pull request by johnnyreilly**
CLOSED IN FAVOUR OF https://github.com/Realytics/fork-ts-checker-webpack-plugin/pull/305

----------------------------------

This PR is intended to start the journey towards adding eslint TypeScript support: 

I'm not sure how long it will take to do this as I'm somewhat time poor right now, so all help is appreciated ❤️ 😄 

So, what's happened so far? This:

1. Disabled `tslint --fix` during commits
2. Added a new project under `/test/integration/` called `project_eslint`.  This contains some simple eslint errors which are visible in VS Code with the ESLint VS Code plugin.  In future the `fork-ts-checker-webpack-plugin` should pick these up when a test exists to exercise this

To be continued....!

### CODE REVIEW

**Comment by johnnyreilly** [comment]
I forgot to catch up my branch with master right from the off - I think I'll close this and start clean later.

**Comment by fabb** [comment]
You can rebase and force push in order to reuse this PR, there would be no need to close this (just saying).

**Comment by johnnyreilly** [comment]
Oh sure it's possible - but starting afresh is just easier. Merging upstream wasn't the straightforward affair I'd hoped (much change since I originally forked)

**Comment by fabb** [comment]
In that case you could also just reset your branch to master, and force push and continue committing from there. 
Anyways, I‘m really looking forward to this PR, cheers!

**Pull request closed without merging**
