### PR TITLE
Sync master & beta

### PR DESCRIPTION
**Pull request by phryneas**
Just to get master and beta back in sync. After this we should be golden.

### CODE REVIEW

**Comment by phryneas** [comment]
@johnnyreilly or @piotr-oles could one of you approve this? Once it is rebased on beta we should be able to avoid future rebase-merge-foo :)

**Review by johnnyreilly — APPROVED** [review]
I approve 😉

**Comment by phryneas** [comment]
*sigh* one of the tests failed because of a random error... o_O I'll try restarting it but I fear I'll have to reopen this.

Once it goes wrong, it keeps going wrong -.-

**Comment by johnnyreilly** [comment]
I have faith 🤞😏

**Comment by phryneas** [comment]
It worked! Wonders *do* happen!

**Comment by johnnyreilly** [comment]
Good things **do** happen to good people! 😀

**Comment by johnnyreilly** [comment]
So just so I'm clear: we think that the path should now be clear to use semantic release (in the way @piotr-oles has helpfully documented) and releases should now take care of themselves?

**Comment by piotr-oles** [comment]
Yup 😄

**Pull request merged**
