### PR TITLE
Emit d.ts files when mode is write-tsbuildinfo

### PR DESCRIPTION
**Pull request by adriangodong**
This PR updates the write logic to also emit files ending with `d.ts` when mode is set to `write-tsbuildinfo`. This allows the plugin to work together with ts-loader or babel-loader and emits `d.ts` files without needing to run `tsc`.

### CODE REVIEW

**Comment by piotr-oles** [comment]
Why don't you use `write-references` instead?

**Comment by adriangodong** [comment]
> Why don't you use `write-references` instead?

Wouldn't that mode overwrite the output of ts-loader?

**Comment by piotr-oles** [comment]
Ah, right. Could you add `write-dts` mode instead to keep it backward compatible?

**Comment by adriangodong** [comment]
Closing this in favor of a new mode, write-dts, implemented in https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/679

**Pull request closed without merging**
